table dBarrio
	lineageTag: 7aae71aa-55a9-45b8-ba4b-3b42de004910

	column ID_Barrio
		dataType: int64
		formatString: 0
		lineageTag: 68ca1617-7ca4-4367-b537-7f496efa4a32
		summarizeBy: none
		sourceColumn: ID_Barrio

		annotation SummarizationSetBy = Automatic

	column NombreBarrio_es
		dataType: string
		lineageTag: 9e8b68c2-8af3-403a-b1c5-5cc0ae00e1e0
		summarizeBy: none
		sourceColumn: NombreBarrio_es

		annotation SummarizationSetBy = Automatic

	column NombreBarrio_eu
		dataType: string
		lineageTag: b9230980-103a-4479-94ae-95a2d874e2b4
		summarizeBy: none
		sourceColumn: NombreBarrio_eu

		annotation SummarizationSetBy = Automatic

	partition dBarrio = m
		mode: import
		source =
				let
				    Origen = Sql.Database("BLACKROSEWARRIO", "AyuntamientoNavarraDB"),
				    dbo_dBarrio = Origen{[Schema="dbo",Item="dBarrio"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_dBarrio,{"fHechos_Incidencias"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

