table dCalendario
	lineageTag: ad265096-86f5-4004-8ece-ec45ac03748a

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4db2c3c6-659e-45cb-9e14-0a00465cef23
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: c5167454-6e57-4488-a15d-049bf772db22
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 8a355a47-1453-48a9-a79e-40fa5b406876
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column NombreMes_es
		dataType: string
		lineageTag: acd07c88-c67a-447f-8beb-36611a3c8693
		summarizeBy: none
		sourceColumn: NombreMes_es

		annotation SummarizationSetBy = Automatic

	column NombreMes_eu
		dataType: string
		lineageTag: f582a6d3-6b9a-473d-9cb0-5376af497724
		summarizeBy: none
		sourceColumn: NombreMes_eu

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    Origen = Sql.Database("BLACKROSEWARRIO", "AyuntamientoNavarraDB"),
				    dbo_dCalendario = Origen{[Schema="dbo",Item="dCalendario"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_dCalendario,{"fHechos_Incidencias"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

