table Product
	lineageTag: 9a9d8d17-750a-454f-bc89-9f42429f42fa

	column ProductKey
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 642ad0fa-3a0a-4b86-8107-1d15c9d17374
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(50)
		lineageTag: 4d31ff9f-7fb2-4810-b1db-870c72b352da
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(15)
		lineageTag: fc9dde8b-3d3d-44b9-95a2-debc42fd9261
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 9da862a4-b5af-448d-af15-ad194d7e0ec9
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 6b93f42f-26b6-4e3d-9020-42f42ca8abf7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Product-a88da2de-9e33-4c15-87fe-b0b05b488e79 = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database("localhost", "AdventureWorksDW2022-DP500"),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_DimProduct, each ([FinishedGoodsFlag] = true)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"ProductKey", "EnglishProductName", "Color", "DimProductSubcategory"}),
				    #"Expanded DimProductSubcategory" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimProductSubcategory", {"EnglishProductSubcategoryName", "DimProductCategory"}, {"EnglishProductSubcategoryName", "DimProductCategory"}),
				    #"Expanded DimProductCategory" = Table.ExpandRecordColumn(#"Expanded DimProductSubcategory", "DimProductCategory", {"EnglishProductCategoryName"}, {"EnglishProductCategoryName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded DimProductCategory",{{"EnglishProductName", "Product"}, {"EnglishProductSubcategoryName", "Subcategory"}, {"EnglishProductCategoryName", "Category"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

