table Territory
	lineageTag: 9e28524d-6f2e-4bc1-877c-2b1db44333e9

	column SalesTerritoryKey
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: bff14db2-9bf1-42ea-a5fb-9ecefc973306
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(50)
		lineageTag: b7a03433-1007-409c-b29c-e3cd65778bec
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(50)
		lineageTag: c5659664-6785-44d2-b435-b5f53ff9fb8b
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: edd52cd9-c9cd-4884-bf4d-fc2a76131e57
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	partition Territory-b395a0dc-762c-4728-8671-71e4d35df1a1 = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database("localhost", "AdventureWorksDW2022-DP500"),
				    dbo_DimSalesTerritory = Source{[Schema="dbo",Item="DimSalesTerritory"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimSalesTerritory,{"SalesTerritoryKey", "SalesTerritoryRegion", "SalesTerritoryCountry", "SalesTerritoryGroup"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"SalesTerritoryRegion", "Region"}, {"SalesTerritoryCountry", "Country"}, {"SalesTerritoryGroup", "Group"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

